# Generated by Django 6.0.2 on 2026-02-26 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('meaning', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('example_translation', models.TextField(blank=True, null=True)),
                ('pronunciation', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_key', models.DateField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_image', models.URLField(blank=True, max_length=500, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vocabularies', to='api.collection')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_instances', to='api.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('learning', 'Đang học'), ('review', 'Ôn tập'), ('mastered', 'Đã thuộc')], default='learning', max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.vocabulary')),
            ],
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'date_key'], name='api_collect_user_id_2a9939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'date_key')},
        ),
        migrations.AddIndex(
            model_name='savedvocabulary',
            index=models.Index(fields=['collection', 'saved_at'], name='api_savedvo_collect_5a8143_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedvocabulary',
            unique_together={('collection', 'vocabulary')},
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'status', 'last_reviewed'], name='api_learnin_user_id_943553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'vocabulary')},
        ),
    ]
