# Generated by Django 6.0.2 on 2026-04-04 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanaCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('hiragana', 'Hiragana'), ('katakana', 'Katakana')], max_length=10)),
                ('romanji', models.CharField(blank=True, max_length=50)),
                ('svg_content', models.TextField()),
                ('unicode_decimal', models.IntegerField(blank=True, null=True, unique=True)),
                ('strokes', models.JSONField(blank=True, default=list)),
                ('total_strokes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('meaning', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('example_translation', models.TextField(blank=True, null=True)),
                ('pronunciation', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_key', models.DateField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonKana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('kana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanacharacter')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='kanas',
            field=models.ManyToManyField(related_name='lessons', through='api.LessonKana', to='api.kanacharacter'),
        ),
        migrations.CreateModel(
            name='SavedVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_image', models.URLField(blank=True, max_length=500, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vocabularies', to='api.collection')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_instances', to='api.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('memorized', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.flashcardset')),
                ('saved_vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set_items', to='api.savedvocabulary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKanaStrokeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_strokes', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('kana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanacharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kana_stroke_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_vocab_learned', models.IntegerField(default=0)),
                ('has_passed_kana_test', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('learning', 'Đang học'), ('review', 'Ôn tập'), ('mastered', 'Đã thuộc')], default='learning', max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.vocabulary')),
            ],
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'date_key'], name='api_collect_user_id_2a9939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'date_key')},
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', 'created_at'], name='api_flashca_user_id_38ebf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardset',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonkana',
            unique_together={('lesson', 'kana')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcardsetitem',
            unique_together={('flashcard_set', 'saved_vocab')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='userkanastrokeprogress',
            unique_together={('user', 'kana')},
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='savedvocabulary',
            index=models.Index(fields=['collection', 'saved_at'], name='api_savedvo_collect_5a8143_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedvocabulary',
            unique_together={('collection', 'vocabulary')},
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'status', 'last_reviewed'], name='api_learnin_user_id_943553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'vocabulary')},
        ),
    ]
