# Generated by Django 6.0.2 on 2026-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='reading_hiragana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
