# Generated by Django 6.0.2 on 2026-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vocabulary_reading_hiragana_vocabulary_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
