# Generated by Django 6.0.4 on 2026-04-28 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_word_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcardsetitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flashcardsetitem',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set_items', to='api.vocabulary'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardsetitem',
            name='saved_vocab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set_items', to='api.savedvocabulary'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'next_review_date'], name='api_learnin_user_id_42a909_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcardsetitem',
            constraint=models.UniqueConstraint(fields=('flashcard_set', 'saved_vocab'), name='unique_set_saved_vocab'),
        ),
        migrations.AddConstraint(
            model_name='flashcardsetitem',
            constraint=models.UniqueConstraint(condition=models.Q(('vocabulary__isnull', False)), fields=('flashcard_set', 'vocabulary'), name='unique_set_vocabulary'),
        ),
    ]
