# Generated by Django 6.0.4 on 2026-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_flashcardsetitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanacharacter',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='kana_audio/'),
        ),
    ]
