# Generated by Django 6.0.4 on 2026-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kanacharacter_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='vocab_audio/'),
        ),
    ]
